### ISSUE TITLE
Mashape "Bad credentials"

### ISSUE THREAD

**Issue by alexwalling** [juanroldan1989/movie_quotes#1]
Hey! I'm trying to use your API through the Mashape Marketplace and I'm getting a response of "Bad credentials" even though it's free on the marketplace. Please advise? 

Link to marketplace: https://market.mashape.com/juanroldan1989/moviequotes

**Comment by juanroldan1989** [comment]
Hey @alexwalling ! 

I've just updated Mashape settings:
https://market.mashape.com/juanroldan1989/moviequotes

Everything's looking good now.

Cheers !
